[package]
name = "macros-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
macros-parsers = { path = "../macros-parsers" }
proc-macro-error = "1.0"
